### ISSUE TITLE
No system tray icon to update theming

### ISSUE THREAD

**Issue by LambLeeg** [avanishsubbiah/material-you-theme#13]
Hello there! I have Fedora SilverBlue, and after installing it works fine, except for the system tray icon. Thus, I have no way to update colors
![image](https://user-images.githubusercontent.com/59935189/182631152-0c0267b4-6c22-4c95-80be-0a916cb757fa.png)

**Comment by DATL4G** [comment]
Same happens to me on Fedora 36

**Comment by avanishsubbiah** [comment]
The extension now uses your system color preference (light/dark) in your settings application, and will automatically update the applied theme when you change the color preference or your wallpaper without needing to manually refresh. So I removed the indicator because it didn't do anything after that addition. See more details in issue #10.

I will be adding a settings menu for the extension for configuring and interacting with it. Maybe I'll add an option to add the indicator back and turn off automatic theme updates in case anyone wants to generate a theme based on one wallpaper and keep that theme on a different wallpaper; however, my other [script](https://github.com/avanishsubbiah/adwaita-materialu) is more appropriate for generating material you themes based on any provided image rather than the currently applied wallpaper.
