### ISSUE TITLE
The shell theme called `MaterialYou` makes GNOME 43's new quick settings menu broken

### ISSUE THREAD

**Issue by huge-pancake** [avanishsubbiah/material-you-theme#48]
## Problem

System info:

- Name: Fedora Linux 38 (Workstation Edition Prerelease)
- GNOME Version: 43.beta
- Windowing System: Wayland

When I find the **shell theme** called `MaterialYou` and apply it, the **quick settings menu** was broken

![image](https://user-images.githubusercontent.com/73375859/187452453-5726bd44-4359-4690-ab7c-3b70468bb59a.png)

## Reference

The normal style

![image](https://t3ka.net/wp-content/uploads/2022/08/Gnome-42-vs-Gnome-43.png)

**Comment by avanishsubbiah** [comment]
I haven't yet made the extension compatible with Gnome 43. It will need to have the new gnome 43 sass and shell theme files in `<EXTENSIONDIR>/shell/43` and compile using those files when run on Gnome 43. Right now it only has the Gnome 42 sass and shell theme files under `<EXTENSIONDIR>/shell/42` because the extension only supports Gnome 42.

**Comment by ardjuh** [comment]
This is now fixed
